const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.COMPOSER_URL||'http://127.0.0.1:8089/');
 await page.locator('[data-brand="lumen"]').click();
 const text=page.locator('#lumen-text'),source=page.locator('#lumen-source'),size=page.locator('#lumen-size'),create=page.locator('#lumen-create');
 const canvas=()=>page.locator('#stage-canvas').evaluate(c=>c.toDataURL());
 const initial=await canvas();await create.click();assert.equal(await text.evaluate(e=>e===document.activeElement),true);assert.equal(await canvas(),initial);
 const sample='Light travels faster than sound. That’s why you see lightning before you hear thunder.';
 await text.fill(sample);await source.fill('Met Office');await create.click();await page.waitForFunction(()=>document.querySelector('#lumen-status').textContent.startsWith('Ready:'));
 assert.deepEqual(await page.locator('#stage-canvas').evaluate(c=>[c.width,c.height]),[1080,1350]);
 const dir=path.resolve(__dirname,'../exports/lumen');fs.mkdirSync(dir,{recursive:true});
 const download=page.waitForEvent('download');await page.locator('#btn-download').click();const d=await download;assert.equal(d.suggestedFilename(),'lumen-fact-1080x1350.png');await d.saveAs(path.join(dir,'lumen-fact-sample.png'));
 const ready=await canvas();await text.fill(sample.repeat(20));await create.click();await page.waitForFunction(()=>document.querySelector('#lumen-status').textContent.includes('too long'));assert.equal(await canvas(),ready);await text.fill(sample);
 await size.fill('35');await create.click();assert.equal(await canvas(),ready);assert.equal(await size.evaluate(e=>e.validity.valid),false);await size.fill('64');
 await page.locator('[data-brand="aura"]').click();await page.locator('[data-brand="lumen"]').click();assert.equal(await text.inputValue(),sample);assert.equal(await source.inputValue(),'Met Office');
 await source.fill('');await create.click();await page.waitForFunction(()=>document.querySelector('#lumen-status').textContent.startsWith('Ready:'));
 await page.locator('#btn-save').click();
 await page.setViewportSize({width:390,height:844});await text.scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(dir,'mobile.png')});
 await page.setViewportSize({width:1280,height:900});await text.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(dir,'desktop.png')});
 const staticPaths=await page.evaluate(()=>[...document.querySelectorAll('script[src],link[rel="stylesheet"]')].map(e=>e.src||e.href));for(const url of staticPaths)assert.equal((await page.request.get(url)).ok(),true);
 assert.deepEqual(errors,[]);console.log('PASS: Lumen manual input, source optional, blank/overflow/size validation, brand-switch draft retention, 1080x1350 PNG, save, mobile, local assets.');
}finally{await browser.close()}})();
